services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: buildingsc02-dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"  