# Generated by Django 5.1.7 on 2025-03-24 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bygning',
            fields=[
                ('bygnignsnr', models.IntegerField(primary_key=True, serialize=False)),
                ('bygningsstatuskode', models.CharField(max_length=5)),
                ('kommune', models.IntegerField()),
                ('bygningstypekode', models.IntegerField()),
                ('anntalboenheter', models.IntegerField()),
                ('antalletasjer', models.IntegerField()),
                ('bebygdareal', models.IntegerField()),
                ('bruksarealtotalt', models.IntegerField()),
                ('bruksarealbolig', models.IntegerField()),
                ('bruksarealannet', models.IntegerField()),
                ('bygdDato', models.DateField()),
                ('naboer', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('bygningid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.bygning')),
            ],
        ),
        migrations.CreateModel(
            name='materiale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('navn', models.CharField(max_length=100)),
                ('forelder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.materiale')),
            ],
        ),
        migrations.CreateModel(
            name='materialer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mengde', models.IntegerField()),
                ('mengdeperm2', models.DecimalField(max_digits=8, decimal_places= 4)),
                ('totalmengde', models.IntegerField()),
                ('bygning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.bygning')),
                ('forelder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.materialer')),
            ],
        ),
        migrations.CreateModel(
            name='rapport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dato', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('postalcode', models.IntegerField()),
                ('postalplace', models.CharField(max_length=100)),
                ('berortbra', models.IntegerField()),
                ('bygningstype', models.CharField(max_length=100)),
                ('konstruksjonstype', models.CharField(max_length=100)),
                ('handtering', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=100)),
                ('bygning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.bygning')),
            ],
        ),
        migrations.CreateModel(
            name='rapportmateriale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planlagtmengde', models.IntegerField()),
                ('faktiskmengde', models.IntegerField()),
                ('mengdeperm2', models.DecimalField(max_digits=8, decimal_places=4)),
                ('mengdetilgjenbruk', models.IntegerField()),
                ('mengdetilanlegg', models.IntegerField()),
                ('anlegg', models.CharField(max_length=100)),
                ('totalmengde', models.IntegerField()),
                ('materiale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.materiale')),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.rapport')),
            ],
        ),
    ]
