# Generated by Django 5.1.7 on 2025-04-07 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bygning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bygnignsnr', models.IntegerField()),
                ('bygningsstatuskode', models.CharField(max_length=5)),
                ('kommune', models.IntegerField()),
                ('bygningstypekode', models.IntegerField()),
                ('anntalboenheter', models.IntegerField()),
                ('antalletasjer', models.IntegerField()),
                ('bebygdareal', models.IntegerField()),
                ('bruksarealtotalt', models.IntegerField()),
                ('bruksarealbolig', models.IntegerField()),
                ('bruksarealannet', models.IntegerField()),
                ('bygdDato', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='koordinater',
            fields=[
                ('bygningid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='App.bygning')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='materialtype',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('navn', models.CharField(max_length=100)),
                ('farlig', models.BooleanField(default=False)),
                ('forelder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.materialtype')),
            ],
        ),
        migrations.CreateModel(
            name='rapport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dato', models.DateField(auto_now_add=True, null=True)),
                ('address', models.CharField(max_length=100)),
                ('postalcode', models.IntegerField()),
                ('postalplace', models.CharField(max_length=100)),
                ('berortbra', models.IntegerField()),
                ('bygningstype', models.CharField(max_length=100)),
                ('konstruksjonstype', models.CharField(max_length=100)),
                ('handtering', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=100)),
                ('bygning', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.bygning')),
            ],
        ),
        migrations.CreateModel(
            name='rapportmateriale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planlagtmengde', models.IntegerField()),
                ('faktiskmengde', models.IntegerField()),
                ('mengdetilgjenbruk', models.IntegerField()),
                ('mengdetilanlegg', models.IntegerField()),
                ('anlegg', models.CharField(max_length=100)),
                ('totalmengde', models.IntegerField()),
                ('materiale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.materialtype')),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.rapport')),
            ],
        ),
        migrations.CreateModel(
            name='materialer',
            fields=[
                ('bygning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='App.bygning')),
                ('mengde', models.IntegerField()),
                ('totalmengde', models.IntegerField()),
                ('type_materiale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.materialtype')),
            ],
        ),
    ]
