# Generated by Django 5.1.7 on 2025-03-25 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='koordinater',
            fields=[
                ('bygningid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='App.bygning')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='materiale',
            name='forelder',
        ),
        migrations.RemoveField(
            model_name='materialer',
            name='forelder',
        ),
        migrations.AlterField(
            model_name='materialer',
            name='bygning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, serialize=False, to='App.bygning'),
        ),
        migrations.CreateModel(
            name='materialtype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('navn', models.CharField(max_length=100)),
                ('forelder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.materialtype')),
            ],
        ),
        migrations.AddField(
            model_name='materialer',
            name='type_materiale',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.materialtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rapportmateriale',
            name='materiale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.materialtype'),
        ),
        migrations.DeleteModel(
            name='coordinates',
        ),
        migrations.DeleteModel(
            name='materiale',
        ),
    ]
