# Generated by Django 5.1.7 on 2025-03-27 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_koordinater_remove_materiale_forelder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='bygning',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.bygning'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='dato',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
