# Generated by Django 5.1.7 on 2025-04-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_materialtype_synlig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bygning',
            name='id',
        ),
        migrations.AlterField(
            model_name='bygning',
            name='bygnignsnr',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
