# Generated by Django 5.1.7 on 2025-03-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_rapport_bygning_alter_rapport_dato'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtype',
            name='farlig',
            field=models.BooleanField(default=False),
        ),
    ]
