# Generated by Django 5.1.7 on 2025-03-27 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_materialtype_farlig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtype',
            name='forelder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.materialtype'),
        ),
    ]
