# Generated by Django 5.1.7 on 2025-04-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_materialtype_forelder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bygning',
            name='bygningstypekode',
            field=models.IntegerField(null=True),
        ),
    ]
