# Generated by Django 5.1.7 on 2025-04-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_materialtype_forelder'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtype',
            name='synlig',
            field=models.BooleanField(default=True),
        ),
    ]
