# Generated by Django 5.1.7 on 2025-04-15 15:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    # replaces = [('App', '0007_splitt_bygning_to_bygningsinfo'), ('App', '0008_make_tilbyggsnr_nullable'), ('App', '0009_alter_byggningsinfo_byggningstypekode')]

    dependencies = [
        ('App', '0006_materialtype_synlig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bygning',
            old_name='bygdDato',
            new_name='byggdato',
        ),
        migrations.RenameField(
            model_name='bygning',
            old_name='bygnignsnr',
            new_name='byggningsnr',
        ),
        migrations.RenameField(
            model_name='koordinater',
            old_name='x',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='koordinater',
            old_name='y',
            new_name='longitude',
        ),
        migrations.RemoveField(
            model_name='bygning',
            name='anntalboenheter',
        ),
        migrations.RemoveField(
            model_name='bygning',
            name='antalletasjer',
        ),
        migrations.RemoveField(
            model_name='bygning',
            name='bebygdareal',
        ),
        migrations.RemoveField(
            model_name='bygning',
            name='bruksarealannet',
        ),
        migrations.RemoveField(
            model_name='bygning',
            name='bruksarealbolig',
        ),
        migrations.RemoveField(
            model_name='bygning',
            name='bruksarealtotalt',
        ),
        migrations.RemoveField(
            model_name='bygning',
            name='bygningsstatuskode',
        ),
        migrations.RemoveField(
            model_name='bygning',
            name='bygningstypekode',
        ),
        migrations.RemoveField(
            model_name='bygning',
            name='kommune',
        ),
        migrations.RemoveField(
            model_name='koordinater',
            name='bygningid',
        ),
        migrations.AddField(
            model_name='bygning',
            name='bygningstatuskode',
            field=models.CharField(default='TB', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='koordinater',
            name='bygning',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='App.bygning'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Byggningsinfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kommuneId', models.IntegerField()),
                ('tilbyggsnr', models.IntegerField(blank=True, null=True)),
                ('byggningstypekode', models.IntegerField(blank=True, null=True)),
                ('bygningstatuskode', models.CharField(max_length=2)),
                ('antallboenheter', models.IntegerField()),
                ('antalletasjer', models.IntegerField()),
                ('bebygdareal', models.IntegerField()),
                ('bruksarealtotalt', models.IntegerField()),
                ('bruksarealbolig', models.IntegerField()),
                ('bruksarealannet', models.IntegerField()),
                ('bygning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.bygning')),
            ],
        ),
    ]
