# Generated by Django 5.1.7 on 2025-04-22 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "App",
            "0007_splitt_bygning_to_bygningsinfo_squashed_0009_alter_byggningsinfo_byggningstypekode",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialer",
            name="bygning",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="App.bygning"
            ),
        ),
    ]
