# Generated by Django 5.1.7 on 2025-04-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_materialer_bygning'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='materialer',
            constraint=models.UniqueConstraint(fields=('bygning', 'type_materiale'), name='unique_bygning_materiale'),
        ),
    ]
